### ISSUE TITLE
Evaluation dataset

### ISSUE THREAD

**Issue by sakshamsingh1** [see2sound/see2sound#2]
Hi, 

Thanks for open-sourcing the wonderful work.

I have a question regarding the dataset used in your paper. Where can we find the "sampled images from Laion400M and web" used to produce the quantitative results?

Did I overlook something, or will you release it later?

Thanks

**Comment by Rishit-dagli** [comment]
No, we have not released these set of images. I however agree it would be useful or just for completeness to also share these images. I will get these released this weekend or the next weekend.

Right now *some* of these are present on https://see2sound.github.io.

**Comment by Rishit-dagli** [comment]
Hey, I released those images: https://huggingface.co/datasets/rishitdagli/see-2-sound-eval
