### ISSUE TITLE
add hf integration

### ISSUE THREAD

**Issue by jadechoghari** [see2sound/see2sound#4]
Hello @Rishit-dagli and team,
Congratulations on this amazing work—the model looks incredible! 🎉 wow!!

You should consider making an native implementation of the see2sound * to HF hub 🤗. It can easily be made compatible natively with the Hugging Face Transformers/Diffusers library.

Will do the work - other folks from HF will be available to help.
From your behalf if any questions arise during the process we can open an issue :)

Soon, it will be easily usable with just one line of code. And nice gradio demo on spaces!!

Best regards,
Jade

**Comment by Rishit-dagli** [comment]
hey Jade,
i had a few questions:

- do you think this best belongs in transformers or diffusers, i would assume diffusers?
- what do you think would be a good first step, should i make an issue on diffusers repository for a new pipeline?
- we also have a hf space: https://huggingface.co/spaces/rishitdagli/see-2-sound, some other folks from huggingface helped us with this.

**Comment by jadechoghari** [comment]
sent on mail!
